---
root: true

env:
  browser: true
  es2022: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: '18.3'

rules:
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/prop-types: off
  react/jsx-props-no-spreading: off
  react/function-component-definition: off
  react/require-default-props: off
  react/no-array-index-key: off
  react/no-unstable-nested-components: off
  react/no-unused-prop-types: off
  react/no-unused-state: off
